name: Telegram Motivational Bot

on:
  schedule:
    - cron: '0 12 * * *'  # 7:00 AM Lima (12:00 UTC)
    - cron: '0 14 * * *'  # 9:00 AM Lima (14:00 UTC)
    - cron: '0 16 * * *'  # 11:00 AM Lima (16:00 UTC)
    - cron: '0 18 * * *'  # 1:00 PM Lima (18:00 UTC)
    - cron: '0 20 * * *'  # 3:00 PM Lima (20:00 UTC)
    - cron: '0 22 * * *'  # 5:00 PM Lima (22:00 UTC)
    - cron: '0 0 * * *'   # 7:00 PM Lima (00:00 UTC siguiente día)
    - cron: '0 3 * * *'   # 10:00 PM Lima (03:00 UTC siguiente día)
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: pip install requests pytz
    - name: Check script existence
      run: |
        if [ -f "motivational_bot.py" ]; then
          echo "Script motivational_bot.py found"
        else
          echo "Error: motivational_bot.py not found"
          exit 1
        fi
    - name: Send Telegram message
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        echo "Starting bot execution at $(date -u)"
        python motivational_bot.py || echo "Script failed with exit code $?"
